apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sri-facturacion-ingress
  annotations:
    # AWS Load Balancer Controller (ALB) - Ingress de capa 7
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
spec:
  ingressClassName: alb
  rules:
    - host: api.sri.ec.gob.ec
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sri-facturacion-service
                port:
                  name: http
