apiVersion: v1
kind: Service
metadata:
  name: sri-facturacion-service
  labels:
    app: sri-facturacion-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: sri-facturacion-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

