apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sri-facturacion
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Proyecto GitOps del microservicio SRI Facturación (multi-cloud EKS/AKS)
  sourceRepos:
    - https://github.com/dacl010811/gitops-multicloud.git
    # Repo Helm de la comunidad Prometheus (Application "monitor")
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: sri-facturacion
    # Stack de observabilidad (Prometheus + Grafana)
    - server: https://kubernetes.default.svc
      namespace: monitoring
  clusterResourceWhitelist:
    # kube-prometheus-stack instala CRDs y recursos cluster-scoped (ClusterRole, etc.)
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
