apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sri-facturacion-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: sri-facturacion
    component: bootstrap
spec:
  project: default
  source:
    repoURL: https://github.com/dacl010811/gitops-multicloud.git
    targetRevision: main
    path: gitops/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
